#!/usr/bin/env python3
"""
player-updated_temp_08.png 를 균등 격자로 분할 (기본 2행 × 8열).

  python3 assets/labs/pxart-creator/pxart_split_PNG_grid.py
  python3 assets/labs/pxart-creator/pxart_split_PNG_grid.py --rows 2 --cols 8 --dir farmers
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    print("pip install pillow", file=sys.stderr)
    raise SystemExit(1) from None

DEFAULT_INPUT = (
    Path(__file__).resolve().parent.parent
    / "pxart-creator"
    / "assets"
    / "stardew"
    / "farmer"
    / "hairs_r0c0.png"
)

DEFAULT_OUT_BASE = Path(__file__).resolve().parent / "out"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("input", nargs="?", type=Path, default=DEFAULT_INPUT)
    ap.add_argument(
        "-o",
        "--out-dir",
        type=Path,
        default=None,
        help="(레거시) 출력 경로를 직접 지정. 미지정 시 --dir 을 out/ 아래 폴더로 사용",
    )
    ap.add_argument(
        "--dir",
        type=str,
        default="farmers",
        help="기본 저장 루트(out/) 기준 하위 폴더명만 지정 (예: --dir hats)",
    )
    ap.add_argument("--rows", type=int, default=2)
    ap.add_argument("--cols", type=int, default=8)
    args = ap.parse_args()

    inp = args.input.resolve()
    if not inp.is_file():
        print(f"없음: {inp}", file=sys.stderr)
        return 1

    out_dir = args.out_dir.resolve() if args.out_dir else (DEFAULT_OUT_BASE / args.dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    out_tag = out_dir.name

    im = Image.open(inp).convert("RGBA")
    w, h = im.size
    if w % args.cols or h % args.rows:
        print(
            f"나눗셈 불가: {w}x{h} 를 cols={args.cols} rows={args.rows} 로 균등 분할할 수 없습니다.",
            file=sys.stderr,
        )
        return 1

    cw, ch = w // args.cols, h // args.rows
    print(f"{inp.name}  {w}x{h}  →  셀 {cw}x{ch}  ({args.rows}행×{args.cols}열)  →  {out_dir}")

    for r in range(args.rows):
        for c in range(args.cols):
            x0, y0 = c * cw, r * ch
            tile = im.crop((x0, y0, x0 + cw, y0 + ch))
            name = f"{out_tag}_r{r}c{c}.png"
            tile.save(out_dir / name, optimize=True)
            print(f"  {name}")

    readme = out_dir / "README.txt"
    readme.write_text(
        f"Split from {inp.name} into {args.rows}x{args.cols} grid, cell {cw}x{ch}.\n"
        f"Generated by assets/labs/pxart-creator/pxart_split_PNG_grid.py\n",
        encoding="utf-8",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
