#!/usr/bin/env python3
"""
Player-(Updated).png 에서 보라색(크로마키) 무효 영역을 제외한 유효 스프라이트 덩어리를
연결 요소별로 잘라 PNG로 저장합니다.

- 무효 색: 이미지 테두리에서 가장 많이 등장한 RGB (스타듀 시트 보라)
- 연결: 8-이웃
- 저장: bbox 안에서 해당 라벨 픽셀만 불투명, 나머지는 투명

사용:
  pip install --user numpy scipy pillow
  python3 scripts/pxart_extract_player_updated_blocks.py

출력 (기본):
  assets/labs/pxart-creator/assets/stardew/Character/Player-Updated-extracted/
    player-updated_temp_00.png ...
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np
from PIL import Image
from scipy import ndimage

DEFAULT_INPUT = (
    Path(__file__).resolve().parent.parent
    / "assets"
    / "labs"
    / "pxart-creator"
    / "assets"
    / "stardew"
    / "Character"
    / "Player-(Updated).png"
)
DEFAULT_OUT = DEFAULT_INPUT.parent / "Player-Updated-extracted"


def dominant_edge_color(rgb: np.ndarray) -> np.ndarray:
    """H×W×3 → 테두리 픽셀에서 최빈 RGB."""
    h, w, _ = rgb.shape
    edge = np.concatenate(
        [
            rgb[0, :, :].reshape(-1, 3),
            rgb[-1, :, :].reshape(-1, 3),
            rgb[:, 0, :].reshape(-1, 3),
            rgb[:, -1, :].reshape(-1, 3),
        ],
        axis=0,
    )
    edge_u8 = edge.astype(np.uint8)
    flat = edge_u8[:, 0].astype(np.uint32) * 65536 + edge_u8[:, 1].astype(np.uint32) * 256 + edge_u8[:, 2]
    vals, counts = np.unique(flat, return_counts=True)
    best = vals[counts.argmax()]
    r = best // 65536
    g = (best // 256) % 256
    b = best % 256
    return np.array([r, g, b], dtype=np.int16)


def main() -> int:
    ap = argparse.ArgumentParser(description="Player-(Updated) 보라 무효영역 기준 블록 추출")
    ap.add_argument("input", nargs="?", type=Path, default=DEFAULT_INPUT)
    ap.add_argument("-o", "--out-dir", type=Path, default=DEFAULT_OUT)
    ap.add_argument("--tol", type=float, default=20.0, help="무효색 거리 허용 (유클리드 RGB)")
    ap.add_argument("--min-area", type=int, default=500, help="이 면적 미만 연결 요소는 버림")
    args = ap.parse_args()

    inp = args.input.resolve()
    if not inp.is_file():
        print(f"파일 없음: {inp}", file=sys.stderr)
        return 1

    out_dir = args.out_dir.resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    im = Image.open(inp).convert("RGB")
    rgb = np.array(im, dtype=np.uint8)
    ref = dominant_edge_color(rgb)
    d = np.linalg.norm(rgb.astype(np.int16) - ref, axis=2)
    content = d > args.tol

    struct = np.ones((3, 3), dtype=int)
    labeled, nlab = ndimage.label(content, structure=struct)
    print(f"void RGB ≈ {tuple(int(x) for x in ref)}  tol={args.tol}  components={nlab}")

    blobs: list[tuple[int, int, int, int, int, int]] = []
    for lab in range(1, nlab + 1):
        ys, xs = np.where(labeled == lab)
        if ys.size == 0:
            continue
        area = ys.size
        if area < args.min_area:
            continue
        y0, y1 = int(ys.min()), int(ys.max())
        x0, x1 = int(xs.min()), int(xs.max())
        blobs.append((y0, x0, y1, x1, area, lab))

    blobs.sort(key=lambda t: (t[0], t[1]))
    print(f"저장 블록 수: {len(blobs)} → {out_dir}")

    for idx, (y0, x0, y1, x1, area, lab) in enumerate(blobs):
        sub_l = labeled[y0 : y1 + 1, x0 : x1 + 1]
        sub_rgb = rgb[y0 : y1 + 1, x0 : x1 + 1]
        mask = sub_l == lab
        sub_d = d[y0 : y1 + 1, x0 : x1 + 1]
        void_here = sub_d <= args.tol

        rgba = np.zeros((sub_rgb.shape[0], sub_rgb.shape[1], 4), dtype=np.uint8)
        rgba[..., :3] = sub_rgb
        # 라벨 안이지만 크로마키에 가까운 픽셀은 투명
        opaque = mask & ~void_here
        rgba[..., 3] = np.where(opaque, 255, 0).astype(np.uint8)

        name = f"player-updated_temp_{idx:02d}.png"
        out_path = out_dir / name
        Image.fromarray(rgba, "RGBA").save(out_path, optimize=True)
        print(f"  {name}  lab={lab} area={area} bbox=({x0},{y0})-({x1},{y1}) size={x1-x0+1}x{y1-y0+1}")

    meta = out_dir / "README.txt"
    meta.write_text(
        "Generated by scripts/pxart_extract_player_updated_blocks.py\n"
        f"source: {inp.name}\n"
        f"void_color_rgb≈{tuple(int(x) for x in ref)} tol={args.tol} min_area={args.min_area}\n"
        "Names are temporary; split/merge as needed for your pipeline.\n",
        encoding="utf-8",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
